# Generated by Django 4.2.16 on 2024-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lr_quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="option1",
            field=models.CharField(default="Option 1", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="option2",
            field=models.CharField(default="Option 2", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="option3",
            field=models.CharField(default="Option 3", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="option4",
            field=models.CharField(default="Option 4", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="created_at",
            field=models.DateField(),
        ),
    ]
